# ---------------------------------------------------------------
# Site Information Settings
# ---------------------------------------------------------------

# Header Menu
menu:
  Home: /
  Archives: /archives
  Categories: /categories
  Tags: /tags
  About: /about
  Resume: /resume/resume.html
  Projects: /projects

#rss: /atom.xml

since: 2017

# Set default keywords (Use a comma to separate)
keywords: ""

# Put your favicon.ico into `hexo-site/themes/hiero/source/` directory.
favicon: css/images/favicon.ico

auto_excerpt:
    enable: true
    lines: 2
# Put your avatar.jpg into `hexo-site/themes/hiero/source/` directory.
# url is target link (E.g. `url: https://hexo.io/logo.svg` or `url: css/images/mylogo.jpg`)
avatar:
  enable: false
  width: 45
  height: 45
  bottom: 0
  url: https://raw.githubusercontent.com/zhongqin0820/zhongqin0820.github.io/source-articles/source/images/favicon.ico


# AboutPage background
about_big_image: https://source.unsplash.com/collection/954550/1920x1080


# Homepage thumbnail
random_thumb: false


# Post Article's Content
post_catalog:
  enable: true


# Content
fancybox: true


# Sidebar
sidebar: left
widgets:
- recent_posts
- category
- tag
- tagcloud
- archive
- social

# Social Links
# Key is the name of FontAwsome icon.
# Value is the target link (E.g. GitHub: https://github.com/iTimeTraveler)
social:
  Github: https://github.com/zhongqin0820
#  Weibo:
#  Twitter:
#  Facebook:
#  Google-plus:
#  Instagram:
#  Pinterest:
#  Flickr:
  rss: /atom.xml
  email: zhongqin0820@163.com


# Search
search:
    insight: true # you need to install `hexo-generator-json-content` before using Insight Search
    swiftype: # enter swiftype install key here
    baidu: false # you need to disable other search engines to use Baidu search, options: true, false


# 阅读更多
excerpt_link: Read More

# comment ShortName, you can choose only ONE to display.
#
gentie_productKey: #your-gentie-product-key
duoshuo_shortname:
disqus_shortname:
livere_shortname: MTAyMC8yOTk4NS82NTUw
uyan_uid:
wumii:

# Code Highlight theme
# Available value:
#    default | normal | night | night eighties | night blue | night bright
# https://github.com/chriskempson/tomorrow-theme
highlight_theme: default



# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive


# widget behavior
archive_type: 'monthly'
show_count: true

# Google Webmaster tools verification setting
# See: https://www.google.com/webmasters/
google_site_verification: "google-site-verification: google2ade42c9eaad51d0.html"
baidu_site_verification: "N7RDvFcI1s"
qihu_site_verification:

# Miscellaneous
google_analytics:
gauges_analytics:
baidu_analytics:
tencent_analytics:
busuanzi_analytics: true
twitter:
google_plus:
fb_admins:
fb_app_id:

# Facebook SDK Support.
# https://github.com/iissnan/hexo-theme-next/pull/410
facebook_sdk:
  enable: false
  app_id:       #<app_id>
  fb_admin:     #<user_id>
  like_button:  #true
  webmaster:    #true

# CNZZ count
cnzz_siteid: 1263278368

# donation button
donate:
    enable: true
    message: '如果觉得我的文章对您有用，请随意打赏。您的支持将鼓励我继续创作!'
    wechatImage: https://raw.githubusercontent.com/zhongqin0820/zhongqin0820.github.io/source-articles/source/images/mm_facetoface_collect_qrcode_1532340710502.png
    alipayImage: https://raw.githubusercontent.com/zhongqin0820/zhongqin0820.github.io/source-articles/source/images/1532340773616.jpg


# Enable baidu push so that the blog will push the url to baidu automatically which is very helpful for SEO
#baidu_push: true

# word_count
word_count: true
read_count: true
total_count: true
